apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:
  route:
    receiver: email
    repeatInterval: 30m
    routes:
      - matchers:
        - name: alertname
        - value: HostHighCpuLoad
      - matchers:
        - name: alertname
        - value: KubernetesPodCrashLooping
        repeatInterval: 10m
  receivers:
    - name: email
      emailConfigs:
      - to: gobiginai@gmail.com
        from: gobiginai@gmail.com
        smarthost: smpt.gmail.com:587
        authUsername: gobiginai@gmail.com
        authIdentity: gobiginai@gmail.com
        authPassword:
        name: gmail-auth
        key: password
